added outputfiles

diff --git a/pearson/Makefile b/pearson/Makefile
--- a/pearson/Makefile
+++ b/pearson/Makefile
@@ -1,90 +1,45 @@
 # Author: David Holmqvist <daae19@student.bth.se>
 
 CXX=g++
-CXXFLAGS=-std=c++17 -g -pg -Wunused -Wall -Wunused -mavx -pthread
+CXXFLAGS=-std=c++17 -g -pg -Wunused -Wall -Wunused -mavx
 
 all: pearson
 
 run: clean all test
 
-compare: clean all testclean target1 comparison
 test: testclean target1 target2 target3 target4
 
-testrun: clean all testclean
-	./pearson data/512.data outputfiles/512.1.data 1
-	sleep 1
-	gprof ./pearson gmon.out > outputfiles/512gprof1.txt
-	sleep 1
-	rm gmon.out
-	sleep 1
-	./pearson data/512.data outputfiles/512.2.data 2
-	sleep 1
-	gprof ./pearson gmon.out > outputfiles/512gprof2.txt
-	sleep 1
-	rm gmon.out
-	sleep 1
-	./pearson data/512.data outputfiles/512.4.data 4
-	sleep 1
-	gprof ./pearson gmon.out > outputfiles/512gprof4.txt
-	sleep 1
-	rm gmon.out
-	sleep 1
-	./pearson data/512.data outputfiles/512.8.data 8
-	sleep 1
-	gprof ./pearson gmon.out > outputfiles/512gprof8.txt
-	sleep 1
-	rm gmon.out
-	sleep 1
-	./pearson data/512.data outputfiles/512.16.data 16
-	sleep 1
-	gprof ./pearson gmon.out > outputfiles/512gprof16.txt
-	sleep 1
-	rm gmon.out
-	sleep 1
-	./pearson data/512.data outputfiles/512.12.data 12
-	sleep 1
-	gprof ./pearson gmon.out > outputfiles/512gprof12.txt
-	sleep 1
-	rm gmon.out
-	sleep 1
-
 target1:
-	./pearson data/128.data outputfiles/128.data 16
+	./pearson data/128.data outputfiles/128.data
 	sleep 1
 	gprof ./pearson gmon.out > outputfiles/128gprof.txt
 	sleep 1
 	rm gmon.out
 
 target2: target1
-	./pearson data/256.data outputfiles/256.data 16
+	./pearson data/256.data outputfiles/256.data
 	sleep 1 
 	gprof ./pearson gmon.out > outputfiles/256gprof.txt
 	sleep 1
 	rm gmon.out
 
 target3: target2
-	./pearson data/512.data outputfiles/512.data 16
+	./pearson data/512.data outputfiles/512.data
 	sleep 1
 	gprof ./pearson gmon.out > outputfiles/512gprof.txt
 	sleep 1
 	rm gmon.out
 
 target4:target3
-	./pearson data/1024.data outputfiles/1024.data 16
+	./pearson data/1024.data outputfiles/1024.data
 	sleep 1
 	gprof ./pearson gmon.out > outputfiles/1024gprof.txt
 	sleep 1
 	rm gmon.out
 	
-
-comparison:
-	@diff -q outputfiles/128.data outputfiles_par/128.data > /dev/null; \
-	if [ $$? -ne 0 ]; then \
-		echo "Error the files are different";\
-		exit 1; \
-	else \
-		echo "success, the files are the same";\
-	fi
+debugg:
+	gdb ./pearson
+	data/128.data outputfiles/debugg128.data
 
 memtest: clean all
 	rm outputfiles/*.data massif*
@@ -93,7 +48,14 @@ memtest: clean all
 	valgrind --tool=massif ./pearson data/512.data outputfiles/512.data
 	valgrind --tool=massif ./pearson data/1024.data outputfiles/1024.data
 
-
+compare:
+	@diff -q outputfiles/128.data outputfiles_par/128.data > /dev/null; \
+	if [ $$? -ne 0 ]; then \
+		echo "Error the files are different";\
+		exit 1; \
+	else \
+		echo "success, the files are the same";\
+	fi
 
 pearson: vector dataset analysis pearson.cpp
 	$(CXX) $(CXXFLAGS) pearson.cpp vector.o dataset.o analysis.o -o pearson
